### ISSUE TITLE
Poloniex WSS ('WebSocket connection upgrade failed (429 - TooManyRequests)')

### ISSUE THREAD

**Issue by JBaczuk** [nlsdfnbch/bitex#105] opened 2017-11-17 21:39 UTC
### Poloniex WSS Error

# Steps to Reproduce
Python 3 in conda environment on Jupyter

The following code:
```
# from bitex.api.WSS import GeminiWSS
from bitex.api.WSS import PoloniexWSS
import time

wss = PoloniexWSS()
wss.start()
time.sleep(5)
wss.stop()

while not wss.data_q.empty():
    print(wss.data_q.get())
```

# Actual Results

Produced:
```
INFO:root:failing WebSocket opening handshake ('WebSocket connection upgrade failed (429 - TooManyRequests)')
INFO:root:failing WebSocket opening handshake ('WebSocket connection upgrade failed (429 - TooManyRequests)')
WARNING:root:dropping connection to peer tcp:104.20.12.48:443 with abort=True: WebSocket connection upgrade failed (429 - TooManyRequests)
INFO:root:failing WebSocket opening handshake ('WebSocket connection upgrade failed (429 - TooManyRequests)')
2017-11-17T21:35:39 failing WebSocket opening handshake ('WebSocket connection upgrade failed (429 - TooManyRequests)')
2017-11-17T21:35:39 failing WebSocket opening handshake ('WebSocket connection upgrade failed (429 - TooManyRequests)')
2017-11-17T21:35:39 dropping connection to peer tcp:104.20.12.48:443 with abort=True: WebSocket connection upgrade failed (429 - TooManyRequests)
```

# Expected Results

A feed similar to Gemini

# Reproducibility

Does it every time

# Additional Information:

I found this module that appears to work, but I'm not sure about the approach if it fits the goals of this repo: [python-poloniex/](https://github.com/s4w3d0ff/python-poloniex/blob/master/examples/ticker/wsDictTicker.py).  For example, it uses the python module [websocket-client
](https://pypi.python.org/pypi/websocket-client).

**Comment by nlsdfnbch** [comment] 2017-11-17 23:45
Hey @JBaczuk,
the above log indicates that you've tried to connect too often. But I'm going to guess it originally is caused by a failed SSL handshake. 

As for the `websocket-client` library, I'm already using it where possible. However, the API endpoint is different for this library from the one you mention. That's why `python-poloniex` can use the websocket client. 
The WS API at `api.poloniex.com` (as compared to `api2.poloniex.com`, which is the one used at `python-poloniex`) uses the `WAMP` protocol, which isn't compatible with the `websocket-client` library.

Finally, the websockets in this library are deprecated and no longer maintained, as I shifted focus to a purely REST-focused framework - so I won't be fixing this issue any time soon. Sorry!

However, if you feel like submitting a PR to fix this, I'll gladly merge it!

**Closed** 2017-11-21 08:43 UTC
Labels: bug, wontfix
