### ISSUE TITLE
Post message failure

### ISSUE THREAD

**Issue by pchandra-uchicago** [nlsdfnbch/bitex#104] opened 2017-11-14 15:10 UTC
Hi Nils,

I am using the rest api v1 to fetch the order status/order history. However I am getting an error
{"message":"Nonce is too small."}. The 'GET' messages work fine though.  I am guessing the multiplier in  nonce() needs to be a bigger number. Am I correct ? I have attached the logs below for your reference.

Thanks
Prakash
[test.log](https://github.com/nlsdfnbch/bitex/files/1471322/test.log)

**Comment by nlsdfnbch** [comment] 2017-11-14 17:35
@pchandra-uchicago,

Practically yes, the `nonce` generated appears to be too small. However, I have implemented the nonce as close as is possible to the javascript implementation (which takes a unix timestamp with millisecond resolution). I have uploaded this fix to production, so you can see if this resolves this issue.

You can, of course, try to manually multiplay by `100000` instead of the currenct `1000` - but I'd rather stick to the suggested implementation. However, if you do find that solves the issue, please do let me know. 

Also, this issue is a duplicate of #97, so have a look at that issue for updates!

**Closed by nlsdfnbch** 2017-11-14 17:35 UTC
