### ISSUE TITLE
Formatted response  - no longer there

### ISSUE THREAD

**Issue by fieldfoxWim** [nlsdfnbch/bitex#107] opened 2017-11-22 20:39 UTC
Hi Nils

I notice that in the master there are formatters to unify the different responses of the exchanges.
However in the release and dev, that concept is completely gone. Only the pairs are formatted.
Is this intended? Is it awaiting to be re-implemented?
What is the intention.

I am just getting familiar with your codebase, considering to contribute while I'm testing.

The sphinx docs can use some love, I could start with that.

But first I would like to understand the functional differences between the different branches....

Cheers
Wim

**Comment by nlsdfnbch** [comment] 2017-11-22 21:21
Hey @fieldfoxWim,
sure thing! 

In principal, I'm trying my best (that is, when I'm not too lazy or too hectic) to follow [nvie.com's branching model](http://nvie.com/posts/a-successful-git-branching-model/). 
That means, `master` contains the latest stable release, and only receives hotfixes; `dev` is the active development branch and represents a `nightly` build (I'm currently not deploying this branch, more on that further down); any `release-X.Y.Z` branch represents the next, feature-complete release candidate (downloadable via `pip` and its `--pre` flag).

Now, that being said about the intentional differences, here are the functional differences, as requested:
 - `master` - current `PyPi` release, containing the old code base and its deprecated modules
 - `dev` - last nightly build which hasn't been looked at in forever; It's a bit of a mess at the moment and I doubt it will be fixed any time before the `release` branch is finally being merged back into `dev` and `master`.
- `release-2.0.0` - contains a complete rewrite of the `master` code base, complete with docs and tests (although those aren't complete themselves each, mind you). This is the code I'm actively working on. If you want to contribute, this is the branch you should familiarize yourself with. 

As for the `FormattedResponse` - I've had difficulties with this. I came to the conclusion that this is, perhaps useful to some, but the general problem is that all the APIs have a very limited set of fields that are available across all of them. So, instead of converting the `requests.Response` Object into a formatted object, I extended `requests.Response` to `APIResponse` object, which essentially just added an attribute to the original class. However, the extension of this was so hacky, and the benefit of it rather minimal, so I opted for dropping the functionality (for now). 

This goes, by the way, for the Websocket APIs as well. Their implementations have been dropped as well due to their hackish nature. I shifted the focus to solid REST interfaces, rather than many half-assed clients for many APIs (pardon my french).

Do feel free to extend the documentation - I'm not an avid docs writer, and if you have the muse for it, any work is very much appreciated. 
Also, if you happen to enjoy writing tests: the test suite is in desperate need of mocked classes to avoid calling the actual API and making it independent of a working internet connection. I'll admit I'm still new to unittesting, and am still very much learning in this field.

Again, thanks for contributing! Hopefully you'll find something on my repo that you consider worth submitting a PR for. 

If you have any more questions, or If I missed answering one, feel free to let me know!

Cheers,
Nils

**Comment by fieldfoxWim** [comment] 2017-11-23 10:18
Hi Nils

Thanks for your elaborate response.

A few remarks/questions

I also try to follow the branching model you mention as much as possible. However it seems odd to me why you did not do the rewrite of the master in the DEV branch, or even a Feature branch.
Cause I expect merging the Master into the DEV branch will not be that straighforward.
If I would contribute, I would normally make a feature branch from DEV, and when finished push it back to DEV, from where it goes to Release and finally Master.

Formatted responses would be a great feature, as this repo would be used as a backend for whatever application. That application could invoke actions that are exchange independent. It is possible that getting the same response for exchange a is only 1 webrequest, and for Exchange B it takes 3. 
However if I want to create a table showing the BTCETH rates across 4 exchanges, I want a uniform response. I 'll have a look on this.

About the sphynx docs, did you intend to auto generate them from the python code? I have no experience doing that, I rather just type docs in rst.

Unit testing is also not my best skill - let me first get familiar with the repo, and think about docs and uniform responses as that is what I need.

Cheers
Wim

**Comment by nlsdfnbch** [comment] 2017-11-23 10:24
@fieldfoxWim,
You would expect that, and rightly so. The truth is that I've been writing and merging code for so long into `release-2.0.0`, that this is practically the dev branch. It's what it started from, originally. I simply branched off `release` too early.`
I will merge it back into dev today and get that cleared up. 

I'd like to autogenerate the reference, yes - but feel free to write any other kind of documentation as you like. 

Cheers,

Nils

**Comment by fieldfoxWim** [comment] 2017-11-24 00:37
Hi Nils

Thanks for the branch cleanup (y)
I forked your repo and started writing docs. I will create PR when it is a bit more mature.

last question before closing this discussion: are your test actually all green?
for me most of them fail, among them even the #106 bug I reported is clearly there as well...

Best regards

**Comment by nlsdfnbch** [comment] 2017-11-24 06:43
They are not :'( 
The problem there being that the unit tests aren't written correctly (as I have learned from various articles and finally the great fireball they fail into currently) - I'm currently querying the real APIs, which I initially thought is a good idea, since I need to verify the authentication methods. 
However, it turned out they often aren't reachable, so tests that pass one day, may fail another day and thus made the build status absolutely unreliable. That's why currently only linters and install tests are run via travis.

#106 is indeed also showing up and I looked into it. It's detected by the tests, but a false positive at that - the pair works in capital letters (which is the source of this bug) as well as lower case letters (which is what the interface expects from the formatter) - the check simply doesn't know that. I will add this info to #106 and fix it today. 

I'll be busy till next wednesday (I have a state examination coming up), so improvements will only trickle in until then - I'll be more active after that exam is over. 

Again, thank you for opening this issue - I somewhat lost sight of the project and what needs to be done, so your input is very valuable. 

Thanks!

Nils

**Comment by bebosudo** [comment] 2017-12-17 22:41
Hey there, I'd really want to re-introduce the `formatted` property to the `ticker` method.

@fieldfoxWim have you already started working on it? Otherwise I'll try.

A quick and dirty solution could be to use `setattr` on the request returned by `ticker`, something like:
```
def ticker(self, pair, *args, **kwargs):
    """Return the ticker for the given pair."""
    req = self.request('ticker/%s/' % pair, params=kwargs)
    formatted_elements = (req.json()["high"], req.json()["low"], None)
    setattr(req, "formatted", formatted_elements)
    return req
```

What do you think @nlsdfnbch?

Otherwise we could create a class `FormattedResponse` which wraps the response and provide access to a `@property` called `formatted`. Any suggestion?

**Comment by nlsdfnbch** [comment] 2017-12-18 07:09
Using `setattr` would be similar to my previous approach In  the current master branch. The problem is that you can't just extend the Response object since it must be built from an already existing requests.Response instance. This requires you to use `getattr` and `setattr` in the constructor, which works but isn't very elegant. 
Also,  the problem of a common set of fields across all exchanges remains. If you have an approach to how to handle that,  I'll gladly have a look at it!

**Comment by mattisback** [comment] 2017-12-18 09:24
I'd be interested in helping out with this as well.  
Is there any reason you need to return a response object? Could there not be some other object that gets returned?  Eg. `BitexResponse` which contains the response as a property and has methods like `formatted`?

I'll take a look at the lack of standard fields across exchanges.  See what similarities there are.  It might be something worth creating a separate issue for as I'm sure there will be some discussion to it.

**Comment by nlsdfnbch** [comment] 2017-12-18 09:34
It seemed silly to create a class for a 2-field container, so Instead I opted to go the other way around. But coming to think of it, that may perhaps be alot simpler, afterall. We could expose the `requests.Response` attributes via `@property` decorators. 

The reason I want to stick to a `requests.Response` object is that this is just an API wrapper. It should return the data as purely as possible, whereas formatted output should be left to the user, or provided optionally. With this in mind, whatever gets returned should at least handle like a `requests.Response`, in order for the user to pretend it is one and his/her code still working without an issue.

I'll open an Issue for this right now.

**Comment by nlsdfnbch** [comment] 2017-12-20 09:49
Closing this, to avoid duplicates

**Closed by nlsdfnbch** 2017-12-20 09:49 UTC
Labels: Discussion
